"""Opt-in browser smoke workflow against an already running local textgen server.

The browser submits server-local corpus paths: client and server must share the
same filesystem. This edits Notebook text, sampling settings, and layout; use a
scratch session. Run from any directory with Playwright and Chromium installed.
"""
import argparse
import json
import re
from pathlib import Path

from playwright.sync_api import expect, sync_playwright


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--url', default='http://127.0.0.1:7860')
    parser.add_argument('--corpus', type=Path, default=Path(__file__).resolve().parents[1] / 'fixtures' / 'rewrite_reference_sentences.txt')
    parser.add_argument('--device', default='cuda:1')
    parser.add_argument('--output-dir', type=Path, default=Path('rewrite-browser-artifacts'))
    args = parser.parse_args()
    args.corpus = args.corpus.expanduser().resolve(strict=True)
    args.output_dir = args.output_dir.expanduser().resolve()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    results = {'url': args.url, 'corpus': str(args.corpus), 'device': args.device}
    try:
        with sync_playwright() as p:
            browser=p.chromium.launch(headless=True,args=['--no-sandbox'])
            page=browser.new_page(viewport={'width':1500,'height':1100})
            page.goto(args.url,wait_until='domcontentloaded')
            page.get_by_role('tab',name='Session',exact=True).click()
            page.get_by_role('checkbox',name='Show two columns in the Notebook tab',exact=True).uncheck()
            page.get_by_role('tab',name='Parameters',exact=True).click()
            seed_setting=page.get_by_role('spinbutton',name='Seed (-1 for random)',exact=True)
            seed_setting.fill('42');seed_setting.press('Tab')
            temperature=page.get_by_role('spinbutton',name='number input for temperature',exact=True)
            temperature.fill('0.3');temperature.press('Tab')
            allowance=page.get_by_role('spinbutton',name='number input for max_new_tokens',exact=True)
            allowance.fill('150');allowance.press('Tab')
            page.get_by_role('checkbox',name='auto_max_new_tokens',exact=True).uncheck()
            page.get_by_role('checkbox',name='Activate text streaming',exact=True).check()
            page.get_by_role('tab',name='Notebook',exact=True).click()
            page.get_by_role('tab',name='Raw',exact=True).click()
            raw=page.locator('#textbox-notebook textarea')
            original='The station had fallen silent. She reluctantly agreed to stay. unfinished tail'
            raw.fill(original)
            page.get_by_role('tab',name='Rewrite',exact=True).click()
            page.get_by_role('checkbox',name='Enable model thinking for this rewrite',exact=True).uncheck()
            page.locator('span:visible').filter(has_text=re.compile(r'^Corpus and embedding settings$')).click()
            device=page.get_by_role('listbox',name='Embedding device',exact=True)
            device.fill(args.device)
            device.press('Enter')
            paths=page.get_by_role('textbox',name=re.compile(r'^Local .txt files or directories'))
            status=page.get_by_role('textbox',name='Status',exact=True)
            build=page.get_by_role('button',name='Build corpus / retry',exact=True)
            paths.fill(str(args.corpus.parent / 'intentionally-missing-rewrite-corpus.txt'))
            build.click()
            expect(status).to_have_value(re.compile(r'INDEX BUILD FAILED:'),timeout=45000)
            expect(build).to_be_enabled()
            results['failure_retry_controls']=True
            print('Failure recovery passed',flush=True)
            paths.fill(str(args.corpus))
            build.click()
            expect(status).to_have_value(re.compile(r'Building corpus'),timeout=10000)
            expect(paths).to_be_disabled()
            expect(page.get_by_role('button',name='Rewrite',exact=True)).to_be_disabled()
            expect(page.get_by_role('textbox',name=re.compile(r'^Optional seed sentence'))).to_be_disabled()
            expect(page.get_by_role('checkbox',name='Join words hyphenated across lines',exact=True)).to_be_disabled()
            expect(page.get_by_role('checkbox',name='Enable model thinking for this rewrite',exact=True)).to_be_disabled()
            expect(page.get_by_role('button',name='Stop generation',exact=True)).to_be_disabled()
            results['build_controls_locked']=True
            expect(status).to_have_value(re.compile(r'Corpus ready:'),timeout=120000)
            expect(paths).to_be_enabled()
            results['cleanup_report'] = page.get_by_role('textbox',name='Cleanup report',exact=True).input_value()
            assert 'Source locations refer to original decoded characters.' in results['cleanup_report']
            print('Real corpus ready',status.input_value(),flush=True)
            page.get_by_role('button',name='Preview references',exact=True).click()
            expect(status).to_have_value(re.compile(r'Retrieved [0-9]+ references. Click Rewrite'),timeout=120000)
            results['references']=page.get_by_role('textbox',name='Retrieved references and sources',exact=True).input_value()
            print('Preview passed',flush=True)
            page.get_by_role('button',name='Rewrite',exact=True).click()
            expect(page.get_by_role('button',name='Rewrite',exact=True)).to_be_disabled(timeout=15000)
            expect(status).to_have_value(re.compile(r'Rewrite applied\.|REWRITE FAILED:'),timeout=120000)
            results['rewrite_status']=status.input_value()
            print('Rewrite status',results['rewrite_status'],flush=True)
            assert results['rewrite_status'].startswith('Rewrite applied'),results['rewrite_status']
            results['replacement']=page.get_by_role('textbox',name='Proposed replacement',exact=True).input_value()
            page.get_by_role('tab',name='Raw',exact=True).click()
            changed=raw.input_value()
            assert changed.startswith('The station had fallen silent. ')
            assert changed.endswith(' unfinished tail')
            assert changed!=original
            results['after']=changed
            page.get_by_role('tab',name='Rewrite',exact=True).click()
            page.get_by_role('button',name='Undo rewrite',exact=True).click()
            expect(status).to_have_value('Rewrite undone.',timeout=20000)
            page.get_by_role('tab',name='Raw',exact=True).click()
            expect(raw).to_have_value(original)
            results['undo']=True
            page.get_by_role('tab',name='Rewrite',exact=True).click()
            page.get_by_role('checkbox',name='Review before applying',exact=True).check()
            page.get_by_role('textbox',name=re.compile(r'^Optional seed sentence')).fill('She hesitated before agreeing to remain.')
            page.get_by_role('button',name='Rewrite',exact=True).click()
            expect(page.get_by_role('button',name='Rewrite',exact=True)).to_be_disabled(timeout=15000)
            expect(status).to_have_value(re.compile(r'Review the result, then click Apply rewrite\.'),timeout=120000)
            page.get_by_role('tab',name='Raw',exact=True).click()
            expect(raw).to_have_value(original)
            raw.fill(original+' external edit')
            page.get_by_role('tab',name='Rewrite',exact=True).click()
            page.get_by_role('button',name='Apply rewrite',exact=True).click()
            expect(status).to_have_value(re.compile(r'Notebook text or prompt changed'),timeout=20000)
            results['stale_preview_protected']=True
            print('Review conflict protection passed',flush=True)
            seed=page.get_by_role('textbox',name=re.compile(r'^Optional seed sentence'))
            proposal=page.get_by_role('textbox',name='Proposed replacement',exact=True)
            rewrite=page.get_by_role('button',name='Rewrite',exact=True)
            def start_rewrite():
                rewrite.click()
                expect(rewrite).to_be_disabled(timeout=15000)
            page.get_by_role('checkbox',name='Review before applying',exact=True).uncheck()
            seed.fill('')
            page.get_by_role('tab',name='Parameters',exact=True).click()
            rate=page.get_by_role('spinbutton',name='number input for Maximum tokens/second',exact=True)
            rate.fill('1');rate.press('Tab')
            page.get_by_role('tab',name='Notebook',exact=True).click()
            start_rewrite()
            expect(status).to_have_value('Generating replacement sentence',timeout=120000)
            expect(proposal).to_have_value(re.compile(r'\S'),timeout=60000)
            page.get_by_role('button',name='Stop generation',exact=True).click()
            expect(status).to_have_value(re.compile(r'^Stopped\.'),timeout=60000)
            page.get_by_role('tab',name='Raw',exact=True).click()
            expect(raw).to_have_value(original+' external edit')
            results['stop_preserved_source']=True
            page.get_by_role('tab',name='Parameters',exact=True).click()
            rate.fill('0');rate.press('Tab')
            page.get_by_role('spinbutton',name='number input for max_new_tokens',exact=True).fill('150')
            page.get_by_role('tab',name='Notebook',exact=True).click()
            page.get_by_role('tab',name='Rewrite',exact=True).click()
            start_rewrite()
            expect(status).to_have_value(re.compile(r'^Rewrite applied\.'),timeout=120000)
            results['stop_retry']=proposal.input_value()
            seed.fill('She hesitated before agreeing to remain.')
            start_rewrite()
            expect(status).to_have_value(re.compile(r'^Rewrite applied\.'),timeout=120000)
            expect(seed).to_have_value('')
            results['manual_seed_applied']=proposal.input_value()
            start_rewrite()
            expect(status).to_have_value(re.compile(r'^Rewrite applied\.'),timeout=120000)
            results['repeat_after_seed']=proposal.input_value()
            print('Stop, retry, seed, repeat passed',flush=True)
            seed.fill('Maria noticed only that the door was open.')
            page.get_by_role('radio',name='tokens',exact=True).check()
            page.get_by_role('spinbutton',name='number input for Generation-token length tolerance',exact=True).fill('0')
            page.get_by_role('button',name='Preview references',exact=True).click()
            expect(status).to_have_value(re.compile(r'Retrieved [0-9]+ references. Click Rewrite'),timeout=120000)
            results['exact_token_references']=page.get_by_role('textbox',name='Retrieved references and sources',exact=True).input_value()
            assert 'generation tokens' in results['exact_token_references']
            page.get_by_role('radio',name='sentences',exact=True).check()
            seed.fill('')
            print('Real generation-token matching passed',flush=True)
            page.get_by_role('tab',name='Parameters',exact=True).click()
            allowance=page.get_by_role('spinbutton',name='number input for max_new_tokens',exact=True)
            allowance.fill('1');allowance.press('Tab')
            page.get_by_role('tab',name='Notebook',exact=True).click()
            page.get_by_role('tab',name='Raw',exact=True).click()
            before_failure=raw.input_value()
            page.get_by_role('tab',name='Rewrite',exact=True).click()
            start_rewrite()
            expect(status).to_have_value(re.compile(r'^REWRITE FAILED:'),timeout=120000)
            page.get_by_role('tab',name='Raw',exact=True).click()
            expect(raw).to_have_value(before_failure)
            results['native_incomplete_output_preserved']=True
            page.get_by_role('tab',name='Parameters',exact=True).click()
            allowance.fill('150');allowance.press('Tab')
            page.get_by_role('tab',name='Notebook',exact=True).click()
            page.get_by_role('tab',name='Rewrite',exact=True).click()
            start_rewrite()
            expect(status).to_have_value(re.compile(r'^Rewrite applied\.'),timeout=120000)
            results['native_failure_retry']=proposal.input_value()
            page.get_by_role('tab',name='Raw',exact=True).click()
            before_custom_stop=raw.input_value()
            page.get_by_role('tab',name='Parameters',exact=True).click()
            custom_stop=page.get_by_role('textbox',name=re.compile(r'^Custom stopping strings'))
            custom_stop.fill('"."');custom_stop.press('Tab')
            page.get_by_role('tab',name='Notebook',exact=True).click()
            page.get_by_role('tab',name='Rewrite',exact=True).click()
            start_rewrite()
            expect(status).to_have_value(re.compile(r'^REWRITE FAILED:'),timeout=120000)
            page.get_by_role('tab',name='Raw',exact=True).click()
            expect(raw).to_have_value(before_custom_stop)
            results['custom_stop_preserved_source']=True
            page.get_by_role('tab',name='Parameters',exact=True).click()
            custom_stop.fill('');custom_stop.press('Tab')
            page.get_by_role('tab',name='Notebook',exact=True).click()
            page.get_by_role('tab',name='Raw',exact=True).click()
            continuation_prompt = 'The quiet station lay beneath the evening sky, and'
            raw.fill(continuation_prompt)
            page.get_by_role('button',name='Generate',exact=True).click()
            expect(raw).not_to_have_value(continuation_prompt,timeout=60000)
            expect(page.get_by_role('button',name='Generate',exact=True)).to_be_visible(timeout=60000)
            results['ordinary_generate_after_rewrite']=raw.input_value()
            print('Native error recovery and ordinary Generate passed',flush=True)
            page.get_by_role('tab',name='Session',exact=True).click()
            page.get_by_role('checkbox',name='Show two columns in the Notebook tab',exact=True).check()
            page.get_by_role('tab',name='Notebook',exact=True).click()
            page.get_by_role('tab',name='Raw',exact=True).click()
            left=page.get_by_role('textbox',name='Input',exact=True)
            output=page.locator('#textbox-default textarea')
            left.fill(original);output.fill('')
            page.get_by_role('tab',name='Rewrite',exact=True).click()
            page.locator('span:visible').filter(has_text=re.compile(r'^Corpus and embedding settings$')).click()
            device=page.get_by_role('listbox',name='Embedding device',exact=True)
            device.fill(args.device);device.press('Enter')
            page.get_by_role('textbox',name=re.compile(r'^Local .txt files or directories')).fill(str(args.corpus))
            page.get_by_role('button',name='Build corpus / retry',exact=True).click()
            expect(status).to_have_value(re.compile(r'Corpus ready:'),timeout=120000)
            start_rewrite()
            expect(status).to_have_value(re.compile(r'^Rewrite applied\.'),timeout=120000)
            page.get_by_role('tab',name='Raw',exact=True).click()
            expect(left).to_have_value(original)
            two_column=output.input_value()
            assert two_column.startswith('The station had fallen silent. ') and two_column.endswith(' unfinished tail')
            results['two_column_rewrite']=two_column
            page.get_by_role('tab',name='Rewrite',exact=True).click()
            page.get_by_role('button',name='Undo rewrite',exact=True).click()
            expect(status).to_have_value('Rewrite undone.',timeout=20000)
            page.get_by_role('tab',name='Raw',exact=True).click()
            expect(output).to_have_value('')
            results['two_column_undo']=True
            page.get_by_role('tab',name='Rewrite',exact=True).click()
            print('Two-column Rewrite/Undo passed',flush=True)
            page.screenshot(path=str(args.output_dir / 'rewrite-workflow.png'),full_page=True)
            print('Browser workflow passed',flush=True)
            browser.close()

    except Exception as exc:
        results['error'] = f'{type(exc).__name__}: {exc}'
        raise
    finally:
        (args.output_dir / 'browser-results.json').write_text(json.dumps(results, indent=2) + '\n', encoding='utf-8')


if __name__ == '__main__':
    main()
